spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:file:./db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 500
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/devdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: devuser
    password: devpassword
  h2:
    console:
      enabled: false
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 500
    open-in-view: false
    defer-datasource-initialization: true