spring:
  datasource:
    local:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    dev:
      url: jdbc:mysql://localhost:3306/devdb
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: devuser
      password: devpassword