spring:
  config:
    activate:
      on-profile: local
jwt:
  secret: ${JWT_SECRET}
  expiration-time: 3600000
---
spring:
  config:
    activate:
      on-profile: dev
jwt:
  secret: ${JWT_SECRET}
  expiration-time: 3600000