server:
    port: 8080
spring:
  profiles:
    active: local
  config:
    import:
      - classpath:/application-jwt.yml
      - classpath:/application-database.yml
      - classpath:/application-oauth2.yml
---
spring:
  config:
    activate:
        on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console

baseUrl: http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: false

baseUrl: http://localhost:8080