server:
    port: 8080
spring:
  profiles:
    active: local
  config:
    import:
      - classpath:/application-jwt.yml
      - classpath:/application-rdb.yml
      - classpath:/application-redis.yml
      - classpath:/application-oauth2.yml
---
spring:
  config:
    activate:
        on-profile: local
logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
---
spring:
  config:
    activate:
      on-profile: dev